### ISSUE TITLE
"make install" copy "pg_amqp.so" to wrong place

### ISSUE THREAD

**Issue by MKo-xx** [omniti-labs/pg_amqp#11]
Hello, 
"make install" copy "pg_amqp.so" to "/usr/lib/postgresql/9.2/lib/src/" instead of "/usr/lib/postgresql/9.2/lib/" and as a result PostgreSQL can't find it.

make install -n | grep pg_amqp.so
/bin/sh /usr/lib/postgresql/9.2/lib/pgxs/src/makefiles/../../config/install-sh -c -m 755  src/pg_amqp.so '/usr/lib/postgresql/9.2/lib/src/pg_amqp.so'

**Comment by apolishch** [comment]
Any plans of fixing this for pgxn?

**Comment by keithf4** [comment]
I was able to install this on CentOS without any issues on 9.4 (9.3 has the Makefile issues I outlined here http://www.keithf4.com/extension-code-organization/ but seems they fixed that in 9.4)

Unable to see any issues with the Makefile in general since it compiles fine normally on both Ubuntu & Red Hat distros. Only pgxn has this issue and I can only assume it's because of the way the OBJS files are explicitly given with a path prefix and pgxn is somehow assuming that's part of the file name as well.

@theory Any idea what the issue may be here and if there's something that has to be fixed on pgxn or for this extension's Makefile?

**Comment by theory** [comment]
@keithf4 I don't maintain the PGXN client, but AFAIK it just does a `make && make install`. Maybe @dvarrazzo can help you? He maintains [pgxnclient](/dvarrazzo/pgxnclient).

**Comment by dvarrazzo** [comment]
As @theory says, pgxnclient does little more than make && make install.

I've seen that happening though: IIRC it was related to how some names in the Makefile are defined: the module name ends up being defined as `src/pg_amqp.so` instead of `pg_amqp.so`. I can't remember in what project  I saw that happening though.

Looking at the Makefile I don't see it wrong though: the commit f79421f5 seems fixing this problem. Too bad it's been there for three years. Maybe pgxnclient is trying to install an out-of-date version? Try `pgxn download` and check if the Makefile works manually.

**Comment by bmoar** [comment]
@dvarrazzo 
Did `pgxn download amqp` and the version downloaded was 0.3.0

`make && make install` fails with
/usr/bin/install: cannot create regular file ‘/usr/lib/postgresql/9.4/lib/src/pg_amqp.so’: No such file or directory
make: *** [install-lib-shared] Error 1

on 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
Linux pg0.lxc 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Whatever pgxnclient is downloading doesn't have the latest fixes, i.e. f79421f59d283e95590695a7cda2e63597436f44

Manually applied the f79421f59d283e95590695a7cda2e63597436f44 fix and away it goes.

**Comment by rodo** [comment]
Same error on Debian Jessie with PostgresSQL 9.4 installed from apt/pgdg, thanks @bmoar I used your fix.

**Comment by keithf4** [comment]
This seems to be an issue with whatever third-party packagers are doing with the files. If anyone can find some consistent issue with the Makefile that we can fix, please let me know. Otherwise, marking this as wontfix and will close if no one responds.

**Comment by theory** [comment]
You mean whatever third-party packagers are doing with the output of `pg_config --libdir`, which I assume pg_amqp depends on?
