### ISSUE TITLE
basic_publish properties

### ISSUE THREAD

**Issue by andreabat** [omniti-labs/pg_amqp#9]
Hello, was wondering if there is a way of specifying properties when publishing.
What I need to do is set the delivery mode to persistent, so that messages on queue survive rabbitmq restart.

**Comment by xolvo** [comment]
+1 for this feature. It would be really great to control message properties

**Comment by keithf4** [comment]
I'll be implementing this recent push request that adds the delivery_mode option as well as a few others. 
https://github.com/omniti-labs/pg_amqp/pull/13
I can see where delivery_mode is quite important, so that's why I'm just getting this simpler request handled for now.  Maybe down the line it could be expanded to allow further properties in a more dynamic way.
